# Generated by Django 5.2 on 2025-05-19 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoplift', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image_url',
        ),
    ]
